#!/usr/bin/env python3
"""
inspect_books.py

Priority 1 Validation Helper for Marked for Death (Stake Math SDK)

PURPOSE:
  This script makes it easy to quickly inspect and validate books generated by
  `run.py` (especially when using small num_sim_args + compression=False for
  manual event ordering validation).

  It focuses on the critical Priority 1 rules from IMPLEMENTATION_MAPPING_v1.2.md:
    - Correct event emission order (reveal -> winInfo/updateTumbleWin -> 
      internal convert_marked -> updateGlobalMult -> tumbleBoard -> set*Win -> finalWin)
    - Marked symbol conversion timing: must happen AFTER win events are emitted
      but BEFORE the corresponding tumbleBoard (and before next reveal).
    - Global multiplier behavior:
        * Base game starts at x1
        * Free spins start at x2 (explicit updateGlobalMult emitted on FS entry)
        * +1 after every paid cascade (carries across spins within an FS round)
        * Never resets between FS spins

  Run this immediately after a small validation `python run.py` to confirm
  the mechanics and book events are correct before scaling up sim counts or
  enabling optimization/upload.

USAGE EXAMPLES:
  python games/marked_for_death/inspect_books.py                    # Just run it! Auto-picks latest book file + shows clean summary
  python games/marked_for_death/inspect_books.py --count 5          # Inspect the 5 most recent book files
  python games/marked_for_death/inspect_books.py --detailed
  python games/marked_for_death/inspect_books.py library/books/books_base.json

SUPPORTED BOOK FORMATS:
  - Uncompressed (recommended for validation): library/books/books_*.json  (JSON array)
  - Compressed / JSONL: library/publish_files/books_*.jsonl.zst or .jsonl

The script is intentionally simple and self-contained so it is easy to extend
with additional checks (e.g. more detailed board state diffing for marked symbols,
FS retrigger counting, wincap verification, etc.).

DEFAULT BEHAVIOR (Summary Mode):
  By default the script is summary-first for practicality with 50+ spins:
  - Prints a compact overall summary (totals, base vs freegame, mult updates,
    marked conversions, issue count).
  - Spins without issues appear as short one-liners: "Spin #N [basegame] - OK"
  - Only spins with problems get full details printed.
  Use --detailed (or --full) to force the verbose per-spin report for everything.
"""

import argparse
import io
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional

try:
    import zstandard as zstd
except ImportError:
    zstd = None  # Will warn if compressed files are encountered


# --------------------------------------------------------------------------- #
# File discovery and loading
# --------------------------------------------------------------------------- #

def find_book_files(count: int = 5) -> List[Path]:
    """Find the most recently modified book files.

    Searches common locations relative to this script and common CWDs.
    Prefers uncompressed .json for validation runs.
    """
    here = Path(__file__).resolve().parent

    # Possible locations (script-relative + common invocation cwds)
    search_dirs = [
        here / "library" / "books",
        here / "library" / "publish_files",
        Path("games/marked_for_death/library/books"),
        Path("games/marked_for_death/library/publish_files"),
        Path("library/books"),
        Path("library/publish_files"),
        here,  # last resort
    ]

    candidates: List[Path] = []
    patterns = ["books_*.json", "books_*.jsonl", "books_*.zst", "*.jsonl.zst", "books_base*"]

    for d in search_dirs:
        if not d.exists():
            continue
        for pat in patterns:
            for p in d.glob(pat):
                if p.is_file():
                    candidates.append(p)

    # Deduplicate by resolved path + sort by mtime (newest first)
    seen = set()
    unique: List[Path] = []
    for p in candidates:
        rp = p.resolve()
        if rp not in seen:
            seen.add(rp)
            unique.append(p)

    unique.sort(key=lambda p: p.stat().st_mtime if p.exists() else 0, reverse=True)
    return unique[: max(count, 1)]


def _load_jsonl_lines(text_stream) -> List[Dict[str, Any]]:
    books = []
    for line in text_stream:
        line = line.strip()
        if line:
            books.append(json.loads(line))
    return books


def load_books(path: Path) -> List[Dict[str, Any]]:
    """Load one or more books from a file.

    Supports:
      - .json (regular JSON array produced with output_regular_json + compression=False)
      - .jsonl (newline-delimited)
      - .jsonl.zst / *.zst (zstandard compressed JSONL)
    """
    p = str(path).lower()

    if p.endswith(".zst") or ".zst" in p:
        if zstd is None:
            raise RuntimeError(
                "zstandard is required to read compressed books. "
                "Install with: pip install zstandard"
            )
        dctx = zstd.ZstdDecompressor()
        with open(path, "rb") as f:
            with dctx.stream_reader(f) as reader:
                text = io.TextIOWrapper(reader, encoding="utf-8")
                return _load_jsonl_lines(text)

    if p.endswith(".jsonl"):
        with open(path, "r", encoding="utf-8") as f:
            return _load_jsonl_lines(f)

    # Regular .json (array or single object)
    data = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(data, list):
        return data
    if isinstance(data, dict):
        return [data]
    return []


# --------------------------------------------------------------------------- #
# Analysis helpers
# --------------------------------------------------------------------------- #

WIN_EVENTS = {"winInfo", "updateTumbleWin", "setWin", "setTumbleWin"}
FREE_SPIN_EVENTS = {
    "freeSpinTrigger", "freeSpinRetrigger", "updateFreeSpin",
    "freeSpinEnd", "enterBonus"
}
END_EVENTS = {"setTotalWin", "finalWin", "freeSpinEnd"}


def _get_game_types(events: List[Dict]) -> List[str]:
    gts = []
    for e in events:
        if e.get("type") == "reveal":
            gt = e.get("gameType") or e.get("gametype")
            if gt and gt not in gts:
                gts.append(gt)
    return gts or ["unknown"]


def _extract_mult_values(events: List[Dict]) -> tuple:
    """Return (update_values, win_meta_values).

    We separate them because winInfo meta.globalMult reflects the multiplier
    *used for that specific win calculation*, while updateGlobalMult carries
    the authoritative new value after each paid cascade.
    """
    updates: List[int] = []
    win_metas: List[int] = []
    for e in events:
        t = e.get("type")
        if t == "updateGlobalMult":
            v = e.get("globalMult")
            if isinstance(v, (int, float)):
                updates.append(int(v))
        elif t == "winInfo":
            for w in (e.get("wins") or []):
                m = w.get("meta", {}).get("globalMult")
                if isinstance(m, (int, float)):
                    win_metas.append(int(m))
    return updates, win_metas


def _compact_sequence(events: List[Dict], max_len: int = 40) -> str:
    seq = [e.get("type", "?") for e in events]
    s = " → ".join(seq)
    if len(s) > max_len:
        s = s[:max_len] + " …"
    return s


def analyze_book(book: Dict[str, Any]) -> Dict[str, Any]:
    """Analyze a single book for ordering, mult, and marked-conversion timing."""
    events: List[Dict] = book.get("events", []) or []
    book_id = book.get("id", "?")
    criteria = book.get("criteria", book.get("betmode", "unknown"))
    payout = book.get("payoutMultiplier", book.get("payout", 0))

    spin_types = _get_game_types(events)
    spin_type_str = " / ".join(spin_types)

    seq = [e.get("type") for e in events]
    seq_str = _compact_sequence(events)

    # FS involvement must be computed early for use in multiplier checks (tolerate FS-start reset to x2)
    involves_fs = any("free" in (s or "").lower() for s in spin_types) or any(
        t in FREE_SPIN_EVENTS for t in seq
    )

    mult_updates, mult_win_metas = _extract_mult_values(events)
    mult_progress = mult_updates  # authoritative for progression + increment checks

    issues: List[str] = []

    # --- Basic structural checks ---
    if not events:
        issues.append("Book has no events")
        return _make_report(book_id, criteria, payout, spin_type_str, mult_progress, seq, seq_str, issues)

    if seq[0] != "reveal":
        issues.append("First event is not 'reveal'")

    # --- Multiplier progression checks ---
    # Expect strictly increasing by 1 on updateGlobalMult events (the source of truth)
    # Exception: FS round start resets to x2 (even if base had higher mult from cascades).
    # We tolerate a drop to exactly 2 at the start of a freegame round.
    update_indices = [i for i, t in enumerate(seq) if t == "updateGlobalMult"]
    for i in range(1, len(mult_updates)):
        prev, cur = mult_updates[i-1], mult_updates[i]
        if cur == prev + 1:
            continue
        if cur == 2 and involves_fs:
            # FS round start at x2 (after possible base growth) - expected reset, not a violation
            continue
        issues.append(f"Multiplier did not increment by +1 (saw {prev} -> {cur})")

    if involves_fs and mult_updates:
        # Look for a 2 appearing reasonably early (for FS start detection)
        early = mult_updates[:4]
        if 2 not in early and not any(m >= 2 for m in early):
            issues.append("Freegame/FS detected but no globalMult=2 observed near start (FS should begin at x2)")

    # --- Cascade / ordering checks (core Priority 1 validation) ---
    # For this game the expected paid-cascade pattern after a win is:
    #   winInfo / updateTumbleWin  -->  updateGlobalMult  -->  tumbleBoard
    # The "convert_marked_to_wild" call happens between them (silent in events).
    win_indices = [i for i, t in enumerate(seq) if t in WIN_EVENTS]
    tumble_indices = [i for i, t in enumerate(seq) if t == "tumbleBoard"]
    update_g_indices = update_indices

    conversion_checks = 0
    conversion_ok = 0

    for ti in tumble_indices:
        preceding_wins = [wi for wi in win_indices if wi < ti]
        if not preceding_wins:
            # tumble with no win is suspicious for a ways game (tumble only follows wins)
            issues.append(f"tumbleBoard (idx {ti}) has no preceding win* event")
            continue

        last_win = preceding_wins[-1]
        inter_updates = [gi for gi in update_g_indices if last_win < gi < ti]

        conversion_checks += 1
        if inter_updates:
            conversion_ok += 1
        else:
            # Only flag as issue when there was a real win (non-zero payout nearby)
            # Some zero-win paths legitimately skip the mult-update + tumble
            if any(e.get("totalWin", 0) > 0 for e in events[max(0, last_win-1):ti+1] if isinstance(e, dict)):
                issues.append(
                    f"Marked conversion timing suspect: tumbleBoard at {ti} "
                    "not preceded by updateGlobalMult after win event"
                )

    # If we saw wins that led to cascades but never saw the expected update->tumble link
    if conversion_checks > 0 and conversion_ok == 0 and any(
        t in ("tumbleBoard", "updateGlobalMult") for t in seq
    ):
        issues.append("No valid win -> updateGlobalMult -> tumbleBoard pattern detected for cascades")

    # updateGlobalMult should normally be preceded by a win in this implementation
    for gi in update_g_indices:
        preceding = [wi for wi in win_indices if wi < gi]
        if not preceding:
            issues.append(f"updateGlobalMult at idx {gi} without a preceding win event")

    # Final sanity: most books should end with a terminal win event
    if seq and seq[-1] not in END_EVENTS:
        # Not always fatal (some paths), but worth noting
        if payout > 0:
            issues.append(f"Book ends with '{seq[-1]}' instead of a terminal win event")

    return _make_report(
        book_id, criteria, payout, spin_type_str,
        mult_updates, seq, seq_str, issues,
        conversion_checks=conversion_checks,
        conversion_ok=conversion_ok,
        involves_fs=involves_fs,
        win_mults_used=mult_win_metas,
    )


def _make_report(
    book_id: Any,
    criteria: str,
    payout: Any,
    spin_type: str,
    mult_progress: List[int],
    seq: List[str],
    seq_str: str,
    issues: List[str],
    **extra,
) -> Dict[str, Any]:
    return {
        "id": book_id,
        "criteria": criteria,
        "payout": payout,
        "spin_type": spin_type,
        "mult_progression": mult_progress,
        "event_sequence": seq,
        "seq_str": seq_str,
        "issues": issues,
        "conversion_checks": extra.get("conversion_checks", 0),
        "conversion_ok": extra.get("conversion_ok", 0),
        "involves_fs": extra.get("involves_fs", False),
        "win_mults_used": extra.get("win_mults_used", []),
    }


def print_book_report(analysis: Dict[str, Any], book_index: int) -> None:
    """Pretty-print a single book's analysis."""
    a = analysis
    header = f"Book #{book_index}  |  id={a['id']}  |  criteria={a['criteria']}  |  payout={a['payout']}"
    print(f"\n{'='*70}")
    print(header)
    print(f"Spin type: {a['spin_type']}")
    print(f"Multiplier updates (new values from updateGlobalMult): {a['mult_progression'] or 'n/a'}")
    if a.get("win_mults_used"):
        print(f"Win meta globalMults (used for individual win calcs): {a['win_mults_used']}")

    print(f"Event sequence: {a['seq_str']}")

    cc = a.get("conversion_checks", 0)
    co = a.get("conversion_ok", 0)
    if cc > 0:
        status = "OK" if co == cc else "ISSUES"
        print(f"Marked conversion windows (win* -> updateGlobalMult -> tumbleBoard): {co}/{cc}  [{status}]")

    if a["issues"]:
        print("PROBLEMS DETECTED:")
        for msg in a["issues"]:
            print(f"  [!] {msg}")
    else:
        print("[OK] No obvious ordering or multiplier issues detected for this spin.")


def print_compact_spin(analysis: Dict[str, Any], book_index: int) -> None:
    """One-line summary for clean spins (used in default summary mode)."""
    a = analysis
    st = a["spin_type"]
    issues = a.get("issues", [])
    mults = a.get("mult_progression") or []
    mult_str = f"mult:{mults}" if mults else "no mult updates"
    if issues:
        # Should not normally be called for issues, but fallback
        print(f"Spin #{book_index} [{st}] - ISSUES ({len(issues)})")
    else:
        print(f"Spin #{book_index} [{st}] - OK  ({mult_str}, payout={a['payout']})")


def print_overall_summary(
    total_spins: int,
    base_only: int,
    fs_involved: int,
    total_mult_updates: int,
    total_conv_ok: int,
    total_conv_checks: int,
    spins_with_issues: int,
    file_count: int,
) -> None:
    """Clean top-level summary (always shown)."""
    print("\n" + "=" * 70)
    print("OVERALL SUMMARY")
    print(f"Files analyzed : {file_count}")
    print(f"Total spins    : {total_spins}")
    print(f"  Basegame only     : {base_only}")
    print(f"  Involving freegame: {fs_involved}")
    print(f"Multiplier updates seen : {total_mult_updates}")
    conv_pct = f" ({total_conv_ok}/{total_conv_checks})" if total_conv_checks else ""
    print(f"Marked conv. windows OK : {total_conv_ok}{conv_pct}")
    print(f"Spins with issues       : {spins_with_issues}")
    print("=" * 70)


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Inspect and validate books generated by run.py for Marked for Death (Priority 1 checks)."
    )
    parser.add_argument(
        "book_path",
        nargs="?",
        help="Path to a specific book file (.json, .jsonl, or .zst)",
    )
    parser.add_argument(
        "--latest", action="store_true",
        help="Force the single most recent book file (same as running with no arguments)."
    )
    parser.add_argument(
        "--count", type=int, default=None,
        help="How many of the newest book *files* to inspect (default when no args: 1 = latest)."
    )
    parser.add_argument(
        "--detailed", "--full", action="store_true", dest="detailed",
        help="Show full detailed report for *every* spin (default is summary mode: "
             "overall stats + only problem spins get details; clean spins are one-liners)."
    )
    args = parser.parse_args(argv)

    if args.book_path:
        files = [Path(args.book_path)]
    elif args.latest:
        files = find_book_files(count=1)
    else:
        # Bare run (or just --detailed etc.) → convenient default: latest file + summary
        n = args.count if args.count is not None else 1
        files = find_book_files(count=n)

    if not files:
        print("No book files found. Run `python run.py` first (with small num_sim_args + compression=False).")
        return 1

    total_spins = 0
    total_issues_count = 0
    display_counter = 0
    base_only = 0
    fs_involved = 0
    total_mult_updates = 0
    total_conv_ok = 0
    total_conv_checks = 0

    print(f"inspect_books.py — Marked for Death Priority 1 validation")
    mode = "detailed" if args.detailed else "summary"
    print(f"Mode: {mode}")

    # Collect everything first (for summary-first output)
    all_analyses: List[Dict[str, Any]] = []

    auto_latest = not args.book_path and not args.latest and args.count is None

    for f in files:
        try:
            books = load_books(f)
            prefix = "Auto-selected latest: " if (auto_latest and len(files) == 1) else ""
            print(f"  - {prefix}{f} ({len(books)} spins)")
        except Exception as exc:
            print(f"\n[ERROR] Failed to load {f}: {exc}")
            continue

        for book in books:
            analysis = analyze_book(book)
            all_analyses.append(analysis)

    # Compute aggregates
    for a in all_analyses:
        total_spins += 1
        if a.get("involves_fs"):
            fs_involved += 1
        else:
            base_only += 1

        mults = a.get("mult_progression") or []
        total_mult_updates += len(mults)

        total_conv_ok += a.get("conversion_ok", 0)
        total_conv_checks += a.get("conversion_checks", 0)

        if a.get("issues"):
            total_issues_count += 1

    # Always print overall summary first
    print_overall_summary(
        total_spins=total_spins,
        base_only=base_only,
        fs_involved=fs_involved,
        total_mult_updates=total_mult_updates,
        total_conv_ok=total_conv_ok,
        total_conv_checks=total_conv_checks,
        spins_with_issues=total_issues_count,
        file_count=len(files),
    )

    # Now print per-spin info
    print("\n--- Per-spin results ---")

    problem_analyses = [(i+1, a) for i, a in enumerate(all_analyses) if a.get("issues")]
    clean_analyses = [(i+1, a) for i, a in enumerate(all_analyses) if not a.get("issues")]

    if args.detailed:
        # Full verbose for all
        for idx, a in enumerate(all_analyses, 1):
            print_book_report(a, idx)
    else:
        # Summary mode: full details ONLY for problems
        if problem_analyses:
            print(f"\nProblems ({len(problem_analyses)} spins):")
            for idx, a in problem_analyses:
                print_book_report(a, idx)
        else:
            print("(no spins with issues)")

        # For clean spins: show one-liners only for "interesting" ones (had cascades/mult)
        # + count the rest. This keeps output short for 50+ spins.
        interesting_clean = [(idx, a) for idx, a in clean_analyses
                             if a.get("mult_progression")]
        plain_clean_count = len(clean_analyses) - len(interesting_clean)

        if interesting_clean:
            print(f"\nClean spins with activity ({len(interesting_clean)}):")
            for idx, a in interesting_clean:
                print_compact_spin(a, idx)

        if plain_clean_count > 0:
            print(f"  + {plain_clean_count} additional clean spins (no mult updates / zero payout, omitted for brevity)")

    # Final note
    print(f"\n{'='*70}")
    if total_issues_count == 0:
        print(f"SUMMARY: {total_spins} spins checked across {len(files)} file(s) — all clean.")
        print("Good to proceed!")
    else:
        print(f"SUMMARY: {total_spins} spins checked, {total_issues_count} with issues.")
        print("See detailed PROBLEM sections above. Use --detailed for everything.")
        print("Re-run small validation with DEBUG=True in gamestate.py for extra context.")

    return 0 if total_issues_count == 0 else 2


if __name__ == "__main__":
    sys.exit(main())